name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download and extract Processing 4
      run: |
        Invoke-WebRequest https://github.com/processing/processing4/releases/download/processing-1292-4.2/processing-4.2-windows-x64.zip -OutFile processing.zip
        Expand-Archive processing.zip -DestinationPath processing
        Remove-Item processing.zip

      
    - name: Build Processing sketch
      run: .\processing\processing-4.2\processing-java.exe --sketch=$pwd\HerderGames --output=$pwd\build --variant=windows-amd64 --force --export
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-sketch
        path: build
